services:
  - type: web
    name: transfer-market
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir config config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
