# Generated by Django 6.0.7 on 2026-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('club', models.CharField(max_length=100)),
                ('transfer_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
